# Overview
## No evidence of sex allocation among three sympatric plovers in Madagascar that vary in mating system
#### Maarten Vervoort, Orsolya Vincze, Callie Gesmundo, Zak Pohlen, Sama Zefania, Tamás Székely, Luke J. Eberhart-Phillips

In this repository you can find all the necessary files needed to reproduce the analyses presented in our paper.

* **Rcode_plover_hatching_sex_ratio.pdf** contains the documented code for all analyses, which can be implemented after downloading the dataset provided in the **`data`** folder.
* **`data`**
    + **plover_chick_data.txt** contains the raw chick data collected from the field. Each row is a single capture of a chick at its nest.  Each chick has a unique identifier "chickID" and each brood has a unique identifier "nestID". The geographic coordinates are also shown as "easting" and "northing" (Coordinate System: UTM Zone 38S Tananarive 1925) which are used to in the map to illustrate the spatial distribution of the nests used in this study. A chick can be one of three plover "species" (Kittlitz's, Madagascar, or White-fronted). "Sex" indicates the molecular sex-type of an individual, "year" indicates the year during which an individual was captured, and "dateinseason" indicates the number of days since the start of the breeding season that an individual hatched. The dummy variables "male" and "female" indicate the sex of an individual with "1" signifing the sex.